# Generated by Django 4.0.1 on 2022-01-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('phone_number', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['name', 'location'],
            },
        ),
    ]
